const FETCH_TIMESLOTS = 'FETCH_TIMESLOTS';
const FETCH_TIMESLOTS_SUCCESS = 'FETCH_TIMESLOTS_SUCCESS';
const FETCH_TIMESLOTS_ERROR = 'FETCH_TIMESLOTS_ERROR';

export { FETCH_TIMESLOTS, FETCH_TIMESLOTS_SUCCESS, FETCH_TIMESLOTS_ERROR };
